version: '3.7'

services:

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    expose:
      - 8000
    volumes:
      - /Users/jboucas/flaski:/flaski
      - /Users/jboucas/flaski_data:/flaski_data
    environment:
      - FLASK_ENV=development
      - MAILSERVER=mail
      - REDIS_PASSWORD=my_redis_password 
      - SESSION_TYPE=redis
      - REDIS_ADDRESS=redis:6379/0
      - MAINDB=flaski
      - MYSQL_ROOT_PASSWORD=mypass
      - DATABASE_URL=mysql+pymysql://root:mypass@mariadb:3306/flaski
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb/server
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=mypass

  redis:
    image: redis
    expose:
      - 6379
    command: redis-server --requirepass my_redis_password

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /Users/jboucas/flaski_data/certificates/cert.pem:/cert.pem
      - /Users/jboucas/flaski_data/certificates/key.pem:/key.pem
      - /Users/jboucas/flaski/services/nginx/flaski.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

