version: '3.7'

services:

 server:
  container_name: server
  image: flaski:0.2
  restart: always
  volumes:
   - data:/flaski_data
  environment:
   - FLASK_ENV=production #development, production
   - ADMINS=flaski@age.mpg.de
   - LOGS=/var/log/flaski/
   - SECRET_KEY=${SECRET_KEY}
   - REDIS_ADDRESS=redis:6379/0
   - REDIS_PASSWORD=${REDIS_PASSWORD}
   - MYSQL_USER=root
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
   - MYSQL_HOST=mariadb
   - MYSQL_PORT=3306
   - MAIL_SERVER=mail.age.mpg.de
   - MAIL_PORT=587
   - MAIL_USE_TLS=1
   - MAIL_USERNAME=flaski@age.mpg.de
   - MAIL_PASSWORD=${MAIL_PASSWORD}
  links:
   - mariadb
   - redis
  depends_on:
   - mariadb
   - redis

 cron-backup:
  container_name: backup
  image: hub.age.mpg.de/backup:0.1
  depends_on:
   - mariadb
  volumes:
   - /srv/backup/mariadb:/backup
   - /srv/backup/data:/databack
   - data:/flaski_data:ro
  environment:
   - MYSQL_HOST=mariadb
   - MYSQL_USER=root
   - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
   - MAX_BACKUPS=15
   - INIT_BACKUP=0
   # Every day at 03:00
   - CRON_TIME=44 13 * * *
   #If set, restores latest backup
   #INIT_RESTORE_LATEST=yes
  restart: unless-stopped
  links:
   - mariadb

 mariadb:
  container_name: mariadb
  image: mariadb:10.4
  restart: always
  volumes:
   - db:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

 redis:
  container_name: redis
  image: redis:5
  restart: always
  command: redis-server --requirepass ${REDIS_PASSWORD}

 nginx:
  container_name: nginx
  image: nginx:alpine
  restart: always
  ports:
   - 80:80
   - 443:443
  volumes:
   - /srv/certs/cert.pem:/certs/cert.pem:ro
   - /srv/certs/privkey.pem:/certs/key.pem:ro
   - /srv/certs/chain.pem:/certs/chain.pem:ro
   - ./services/nginx/flaski.conf:/etc/nginx/conf.d/default.conf:ro
  links:
   - server
  depends_on:
   - server

volumes:
 data:
  external: false
 db:
  external: false
 backups:
  external: false
