version: '3.7'

services:

  server:
    #image: jorgeboucas/image_drops:flaski-server
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 443
    volumes:
      - ./:/flaski
      - data:/flaski_data/users/
      #- ./utils/private.apps.tsv:/private.apps.tsv
    environment:
      - FLASK_ENV=production #development, production
      - ADMINS=jboucas@age.mpg.de,jorge.boucas@age.mpg.de
      - REDIS_ADDRESS=redis:6379/0
      - REDIS_PASSWORD=my_redis_password 
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MAIL_SERVER=smtp.googlemail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=1
      - MAIL_USERNAME=bioflaski@gmail.com
      - MAIL_PASSWORD=$EMAILPASS
      #- PRIVATE_APPS=/private.apps.xlsx
    depends_on:
      - mariadb
      - redis
  
  backup:
    #image: hub.age.mpg.de/flaski/backup
    build:
      context: ./services/backup
      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
    volumes:
      - data:/flaski_data/users/
      - backups:/backups
    depends_on:
      - server
      - mariadb

  mariadb:
    image: mariadb/server
    restart: always
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypass

  redis:
    image: redis
    restart: always
    expose:
      - 6379
    command: redis-server --requirepass my_redis_password

  nginx:
    # image: hub.age.mpg.de/flaski/nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
     - /Users/jboucas/flaski_data/certificates/cert.pem:/cert.pem
     - /Users/jboucas/flaski_data/certificates/key.pem:/key.pem
     - ./services/nginx/dhparam.pem:/dhparam.pem
     - ./services/nginx/flaski.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

volumes:
  data:
    external: false
  db:
    external: false
  backups:
    external: false