version: '3.7'

services:

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 443
    volumes:
      - ./:/flaski
      - data:/flaski_data/users/
      #- ./utils/private.apps.tsv:/private.apps.tsv
    environment:
      - FLASK_ENV=development
      - ADMINS=jboucas@age.mpg.de,jorge.boucas@age.mpg.de
      - REDIS_ADDRESS=redis:6379/0
      - REDIS_PASSWORD=my_redis_password 
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_HOST=mariadb
      - MYSQL_PORT=3306
      - MAIL_SERVER=smtp.googlemail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=1
      - MAIL_USERNAME=bioflaski@gmail.com
      - MAIL_PASSWORD=$EMAILPASS
      #- PRIVATE_APPS=/private.apps.xlsx
    depends_on:
      - mariadb
      - redis
  
  backup:
    build:
      context: ./services/backup
      dockerfile: Dockerfile
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_HOST=haproxy
      - MYSQL_PORT=3306
    volumes:
      - data:/flaski_data/users/
      - backups:/backups
      - ./services/backup/run-backups.sh:/run-backups.sh
    depends_on:
      - server
      - mariadb

  # haproxy:
  #   image: haproxy
  #   expose:
  #     - 3306
  #   volumes:
  #     - ./services/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  #   command: 'haproxy -f /usr/local/etc/haproxy/haproxy.cfg'
  #   depends_on:
  #     - mariadb-galera
  #     - mariadb-galera-1
  
  # mariadb-galera:
  #   image: bitnami/mariadb-galera
  #   environment:
  #     - MARIADB_USER=my_user
  #     - MARIADB_PASSWORD=my_password
  #     - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
  #     - MARIADB_GALERA_CLUSTER_NAME=my_galera
  #     - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
  #     - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
  #     - MARIADB_ROOT_PASSWORD=mypass
  #     - MARIADB_USER=root
  #     - MARIADB_PASSWORD=mypass
  #     - MARIADB_DATABASE=my_database

  # mariadb-galera-1:
  #   image: bitnami/mariadb-galera
  #   environment:
  #     - MARIADB_GALERA_CLUSTER_NAME=my_galera
  #     - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera
  #     - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
  #     - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
  #   depends_on:
  #     - mariadb-galera
    
  mariadb:
    image: mariadb/server
    restart: always
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypass

  # dbslave_1:
  #   image: mariadb/server
  #   restart: always
  #   expose:
  #     - 3306
  #     - 4444 
  #     - 4567 
  #     - 4568
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=mypass
  #   volumes:
  #     - ./services/dbslave/my.cnf:/etc/mysql/my.cnf
  #   depends_on:
  #     - mariadb

  redis:
    image: redis
    restart: always
    expose:
      - 6379
    command: redis-server --requirepass my_redis_password

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /Users/jboucas/flaski_data/certificates/cert.pem:/cert.pem
      - /Users/jboucas/flaski_data/certificates/key.pem:/key.pem
      - ./services/nginx/dhparam.pem:/dhparam.pem
      - ./services/nginx/flaski.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

volumes:
  data:
    external: false
  db:
    external: false
  backups:
    external: false