version: '3.7'

services:

 init:
  container_name: init
  image: flaski/flaski:latest # prod
  user: root
  volumes:
   - data:/flaski_data/users:ro
   - /srv/backup/data/users:/backup/users_data # prod (backup  /databack)
   - /srv/backup/mariadb:/backup/mariadb # prod (backup  /databack)
  environment:
   FLASK_ENV: init
   RESTORE_DB: 1
   RESTORE_USERS_DATA: 1
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   SECRET_KEY: ${SECRET_KEY}
   REDIS_ADDRESS: redis:6379/0
   REDIS_PASSWORD: ${REDIS_PASSWORD}
   MYSQL_USER: flaski
   MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
   MYSQL_HOST: mariadb
   MYSQL_PORT: 3306
   MAIL_PORT: 587
   MAIL_USE_TLS: 1
   MAIL_PASSWORD: ${MAIL_PASSWORD}
   # production envs
   ADMINS: flaski@age.mpg.de
   MAIL_SERVER: mail.age.mpg.de
   MAIL_USERNAME: flaski@age.mpg.de
   # development envs
   #ADMINS: jboucas@age.mpg.de
   #MAIL_SERVER: smtp.googlemail.com
   #MAIL_USERNAME: bioflaski@gmail.com
  links:
   - mariadb
  depends_on:
   - mariadb

 server:
  container_name: server
  image: flaski/flaski:latest
  restart: always
  volumes:
   - data:/flaski_data/users
  environment:
   LOGS: /var/log/flaski/
   SECRET_KEY: ${SECRET_KEY}
   REDIS_ADDRESS: redis:6379/0
   REDIS_PASSWORD: ${REDIS_PASSWORD}
   MYSQL_USER: flaski
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_HOST: mariadb
   MYSQL_PORT: 3306
   MAIL_PORT: 587
   MAIL_USE_TLS: '1'
   MAIL_PASSWORD: ${MAIL_PASSWORD}
   #PRIVATE_APPS: /private.apps.xlsx
   # production envs
   FLASK_ENV: production
   ADMINS: flaski@age.mpg.de
   MAIL_SERVER: mail.age.mpg.de
   MAIL_USERNAME: flaski@age.mpg.de
   # development envs
   #FLASK_ENV: development
   #- ADMINS=jboucas@age.mpg.de
   #- MAIL_SERVER=smtp.googlemail.com
   #- MAIL_USERNAME=bioflaski@gmail.com
  links:
   - mariadb
   - redis
  depends_on:
   - init
   - mariadb
   - redis

 backup:
  container_name: backup
  image: flaski/backup:latest
  depends_on:
   - mariadb
   - init
  volumes:
   - /srv/backup/mariadb:/backup/mariadb
   - /srv/backup/data/users:/backup/users_data
   - data:/flaski_data/users:ro
  environment:
   MYSQL_HOST: mariadb
   MYSQL_USER: flaski
   MYSQL_PASS: ${MYSQL_PASSWORD}
   MAX_BACKUPS: 15
   INIT_BACKUP: 0
   # Every day at 03:00
   CRON_TIME: '44 13 * * *'
   #If set, restores latest backup
   #INIT_RESTORE_LATEST=yes
  restart: unless-stopped
  links:
   - mariadb

 mariadb:
  container_name: mariadb
  image: mariadb:10.4
  restart: always
  volumes:
   - db:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

 redis:
  container_name: redis
  image: redis:5
  restart: always
  command: redis-server --requirepass ${REDIS_PASSWORD}

 nginx:
  container_name: nginx
  image: nginx:alpine
  restart: always
  ports:
   - 80:80
   - 443:443
  volumes:
   - /srv/certs/cert.pem:/certs/cert.pem:ro
   - /srv/certs/privkey.pem:/certs/key.pem:ro
   - /srv/certs/chain.pem:/certs/chain.pem:ro
   - ./services/nginx/flaski.conf:/etc/nginx/conf.d/default.conf:ro
  links:
   - server
  depends_on:
   - server

volumes:
 data:
  external: false
 db:
  external: false

